DROP TABLE IF EXISTS words;

CREATE EXTERNAL TABLE words(word STRING, vector ARRAY<float>) 
PARTITIONED BY(id INT)
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ':'
COLLECTION ITEMS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/usr/words';

MSCK REPAIR TABLE words;